2020-01-07 14:54:50,773 - D:\python_project\zidonghua\TestCase\test01case.py[line:45) - DEBUG:登录成功]
2020-01-07 14:54:50,773 - D:\python_project\zidonghua\TestCase\test01case.py[line:45) - DEBUG:登录成功]
2020-01-07 14:54:50,778 - D:\python_project\zidonghua\TestCase\test01case.py[line:48) - DEBUG:参数错误]
2020-01-07 14:54:50,778 - D:\python_project\zidonghua\TestCase\test01case.py[line:48) - DEBUG:参数错误]
2020-01-07 14:54:50,782 - D:\python_project\zidonghua\TestCase\test01case.py[line:51) - DEBUG:参数为空111111]
2020-01-07 14:54:50,782 - D:\python_project\zidonghua\TestCase\test01case.py[line:51) - DEBUG:参数为空111111]
